spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:tst}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: ${DATABASE_SCHEMA}
      jdbc.batch_size: ${DATASOURCE_BATCH_SIZE:50}
      order_inserts: true
      order_updates: true
    show-sql: false

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG




